version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - romainv
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - romainv
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - romainv
