name: Publish
on:
  push:
    branches:
      - production
  workflow_dispatch: # Enable to trigger the workflow manually

env:
  NODE_VERSION: 18

permissions:
  contents: write    

jobs:
  check:
    uses: ./.github/workflows/check.yaml # Reuse the checks workflow

  publish:
    needs: check # Only publish if the checks are successful
    runs-on: ubuntu-latest
    concurrency: npm-publish # Only allow one job to run at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - run: npm test --if-present
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
